# Generated by Django 5.1.8 on 2026-04-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Office", "Office"),
                            ("Travel", "Travel"),
                            ("Software", "Software"),
                            ("Utilities", "Utilities"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("expense_date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
    ]
